image: node:alpine

stages:
  - lint
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest

lint:
  stage: lint
  script:
    - npm ci
    - npm install eslint 
    - npm install eslint-plugin-react@latest
    - eslint --fix --max-warnings 20 src/ || echo "Skipping errors for now..."

test:
  stage: test
  script:
    - npm ci 
    - npx jest --ci

deploy:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive
