image: node:latest

stages:
  - lint
  - test
  - docker
  - deploy

.lint:
  stage: lint
  script:
    - npm install eslint -g
    - cd mylife/
    - npm install -g --only=dev
    - npm install eslint-plugin-react@latest
    - eslint --fix --max-warnings 20 src/ || echo "Skipping errors for now..."

test:
  stage: test
  script:
    - echo "Testing..."

# build-android:
#   stage: build
#   image: node
#   script:
#     - cd mylife/
#     - npm install -g
#     - npm install -g expo-cli
#     - npm run build-android
#   artifacts:
#     paths:
#       - mylife/android-build/
#     expire_in: 1 week

# build-ios:
#   stage: build
#   image: node
#   script:
#     - cd mylife/
#     - npm install -g
#     - npm install -g expo-cli
#     - npm run build-ios
#   artifacts:
#     paths:
#       - mylife/android-ios/
#     expire_in: 1 week

.docker:
  stage: docker
  image: docker:stable
  only:
    - master
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - echo "Building and uploading Docker image 🐳"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH

.deploy:
  stage: deploy
  trigger: my-life-ua/compose
  only:
    - master
